# Puerto por defecto para MQTT
listener 1883
socket_domain ipv4

# Permitir conexiones anonimas
allow_anonymous true

# Configuracion  persistencia
persistence true
persistence_location /mosquitto/data/

# Ruta de los logs
log_dest file /mosquitto/log/mosquitto.log
