<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.4.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="MongoDB.AspNetCore.OData" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnergyMetersService.Application\EnergyMetersService.Application.csproj" />
    <ProjectReference Include="..\EnergyMetersService.Domain\EnergyMetersService.Domain.csproj" />
    <ProjectReference Include="..\EnergyMetersService.Infraestructure\EnergyMetersService.Infraestructure.csproj" />
  </ItemGroup>

</Project>
